### ISSUE TITLE
Correct systemd setup

### ISSUE THREAD

**Issue by txomon** [abaez/docker-shout#1]
Hi, just in case, the best way to do systemd setup would be:
- Copy service file to systemd dir
- systemctl daemon-reload # old versions do require this
- systemctl enable docker-shout@9000

That will create the symlink

**Comment by abaez** [comment]
Hi @txomon, thanks for the advice. You're right. That is the correct way to do it. 

However, say you want to have a direct interpolation with the source version. You will have to copy each time you want to get an update on the versioning, before you do the standard `daemon-reload`. Also, what if you running the service as a local user instead of system wide? You'll get one heck of drinking game from the copy referencing each time.

Still, you are right about the standardized way of doing a service addition.  People that want to do it the `other` way should already know how. Fixed!

**Comment by txomon** [comment]
Users can install in their home files and symlink equally, systemd will
just execute the commands as the user, and as long as it has docker
permission, everything will be fine.
